services:
  mysql:
    image: mysql:8.4
    container_name: smarttask-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Harshal@123"
      MYSQL_DATABASE: smarttask
    ports:
      - "3306:3306"
    volumes:
      - smarttask_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pHarshal@123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

volumes:
  smarttask_mysql_data:
